### PR TITLE
Add documentation, requirement files and .gitignore

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @hmeine 

@zachmullen This includes the "how to make a release"

**Comment by jcfr** [comment]
@zachmullen I will also enable readthedocs

**Comment by jcfr** [comment]
As soon as this is merged, documentation will be available on readthedocs: https://readthedocs.org/projects/ctk-cli/builds/

**Comment by zachmullen** [comment]
Awesome! LGTM

**Pull request merged**
