### PR TITLE
Added a command-line argument parser based on slicer execution model xml spec

### PR DESCRIPTION
**Pull request by cdeepakroy**
This is to allow people to write CLIs in python.

@jcfr @hmeine can you please take a look?

### CODE REVIEW

**Comment by cdeepakroy** [comment]
Below is the output of `python ExecutionModelTour.py --help` for [ExecutionModelTour.xml](https://github.com/Slicer/Slicer/blob/master/Modules/CLI/ExecutionModelTour/ExecutionModelTour.xml):

```
usage: ExecutionModelTour.py [-h] [-V] [--xml] [-i <integer>] [-d <double>]
                             [-f <float-vector>]
                             [--string_vector <string-vector>]
                             [-e {Ron,Eric,Bill,Ross,Steve,Will}]
                             [--boolean1 <boolean>] [--boolean2 <boolean>]
                             [--boolean3 <boolean>] [--file1 <file>]
                             [--files <file>] [--directory1 <directory>]
                             [--image1 <image>] [--image2 <image>]
                             [--transform1 <transform>]
                             [--transform2 <transform>] [--seed <point>]
                             [--seedsFile <pointfile>]
                             [--seedsOutFile <pointfile>] [--region <region>]
                             [--inputFA <measurement>]
                             [--outputFA <measurement>] [--inputDT <table>]
                             [--outputDT <table>]
                             [--returnparameterfile RETURNPARAMETERFILE]
                             arg0 arg1

positional arguments:
  arg0                  First index argument is an image
  arg1                  Second index argument is an image

optional arguments:
  -h, --help            show this help message and exit
  -V, --version         show program's version number and exit
  --xml                 Produce xml description of command line arguments
  -i <integer>, --integer <integer>
                        An integer without constraints (default: 30)
  -d <double>, --double <double>
                        A double with constraints (default: 30.0)
  -f <float-vector>     A vector of floats (default: [1.3, 2.0, -14.0])
  --string_vector <string-vector>
                        A vector of strings (default: ['foo', 'bar',
                        'foobar'])
  -e {Ron,Eric,Bill,Ross,Steve,Will}, --enumeration {Ron,Eric,Bill,Ross,Steve,Will}
                        An enumeration of strings (default: Bill)
  --boolean1 <boolean>  A boolean default true (default: True)
  --boolean2 <boolean>  A boolean default false (default: False)
  --boolean3 <boolean>  A boolean with no default, should be defaulting to
                        false
  --file1 <file>        An input file (file-extensions: ['.png', '.jpg',
                        '.jpeg', '.bmp', '.tif', '.tiff', '.gipl', '.dcm',
                        '.dicom', '.nhdr', '.nrrd', '.mhd', '.mha', '.mask',
                        '.hdr', '.nii', '.nii.gz', '.hdr.gz', '.pic', '.lsm',
                        '.spr', '.vtk', '.vtkp', '.vtki', '.stl', '.csv',
                        '.txt', '.xml', '.html'])
  --files <file>        Multiple input files (accepted multiple times) (file-
                        extensions: ['.png', '.jpg', '.jpeg', '.bmp', '.tif',
                        '.tiff', '.gipl', '.dcm', '.dicom', '.nhdr', '.nrrd',
                        '.mhd', '.mha', '.mask', '.hdr', '.nii', '.nii.gz',
                        '.hdr.gz', '.pic', '.lsm', '.spr', '.vtk', '.vtkp',
                        '.vtki', '.stl', '.csv', '.txt', '.xml', '.html'])
  --directory1 <directory>
                        An input directory. If no default is specified, the
                        current directory is used,
  --image1 <image>      An input image
  --image2 <image>      An output image
  --transform1 <transform>
                        An input transform
  --transform2 <transform>
                        An output transform
  --seed <point>        Lists of points in the CLI correspond to slicer
                        fiducial lists (accepted multiple times) (default:
                        [0.0, 0.0, 0.0])
  --seedsFile <pointfile>
                        Test file of input fiducials, compared to seeds (file-
                        extensions: ['.fcsv'])
  --seedsOutFile <pointfile>
                        Output file to read back in, compare to seeds with
                        flipped settings on first fiducial (file-extensions:
                        ['.fcsv'])
  --region <region>     List of regions to process (accepted multiple times)
  --inputFA <measurement>
                        Array of FA values to process
  --outputFA <measurement>
                        Array of processed (output) FA values
  --inputDT <table>     Array of Table values to process
  --outputDT <table>    Array of processed (output) Table values
  --returnparameterfile RETURNPARAMETERFILE
                        Filename in which to write simple return parameters
                        (integer, float, integer-vector, etc.) as opposed to
                        bulk return parameters (image, file, directory,
                        geometry, transform, measurement, table).

Title: Execution Model Tour

Description: Shows one of each type of parameter.

Author(s): Daniel Blezek (GE), Bill Lorensen (GE)

Acknowledgements: This work is part of the National Alliance for Medical Image
Computing (NAMIC), funded by the National Institutes of Health through the NIH
Roadmap for Medical Research, Grant U54 EB005149.
```

**Comment by cdeepakroy** [comment]
As a comparison below is the output of `ExecutionModelTour --help` generated by [GenerateCLP](https://github.com/Slicer/SlicerExecutionModel/tree/master/GenerateCLP):

```
USAGE: 

   ExecutionModelTour  [--returnparameterfile <std::string>]
                       [--processinformationaddress <std::string>] [--xml]
                       [--echo] [--outputFA <std::string>] [--inputFA
                       <std::string>] [--region
                       <std::vector<std::vector<float> >>] ...  [--seed
                       <std::vector<std::vector<float> >>] ... 
                       [--transform2 <std::string>] [--transform1
                       <std::string>] [--image2 <std::string>] [--image1
                       <std::string>] [--directory1 <std::string>] [--files
                       <std::vector<std::string>>] ...  [--file1
                       <std::string>] [--boolean3] [--boolean2]
                       [--boolean1] [-e <Ron|Eric|Bill|Ross|Steve|Will>]
                       [--string_vector <std::vector<std::string>>] [-f
                       <std::vector<float>>] [-d <double>] [-i <int>] [--]
                       [--version] [-h] <std::string> <std::string>


Where: 

   --returnparameterfile <std::string>
     Filename in which to write simple return parameters (int, float,
     int-vector, etc.) as opposed to bulk return parameters (image,
     geometry, transform, measurement, table).

   --processinformationaddress <std::string>
     Address of a structure to store process information (progress, abort,
     etc.). (default: 0)

   --xml
     Produce xml description of command line arguments (default: 0)

   --echo
     Echo the command line arguments (default: 0)

   --outputFA <std::string>
     Array of processed (output) FA values

   --inputFA <std::string>
     Array of FA values to process

   --region <std::vector<std::vector<float> >>  (accepted multiple times)
     List of regions to process

   --seed <std::vector<std::vector<float> >>  (accepted multiple times)
     Lists of points in the CLI correspond to slicer fiducial lists
     (default: None)

   --transform2 <std::string>
     An output transform

   --transform1 <std::string>
     An input transform

   --image2 <std::string>
     An output image

   --image1 <std::string>
     An input image

   --directory1 <std::string>
     An input directory. If no default is specified, the current directory
     is used,

   --files <std::vector<std::string>>  (accepted multiple times)
     Multiple input files

   --file1 <std::string>
     An input file

   --boolean3
     A boolean with no default, should be defaulting to false

   --boolean2
     A boolean default false (default: 0)

   --boolean1
     A boolean default true (default: 0)

   -e <Ron|Eric|Bill|Ross|Steve|Will>,  --enumeration <Ron|Eric|Bill|Ross
      |Steve|Will>
     An enumeration of strings (default: Bill)

   --string_vector <std::vector<std::string>>
     A vector of strings (default: foo,bar,foobar)

   -f <std::vector<float>>,  -- <std::vector<float>>
     A vector of floats (default: 1.3,2,-14)

   -d <double>,  --double <double>
     A double with constraints (default: 30)

   -i <int>,  --integer <int>
     An integer without constraints (default: 30)

   --,  --ignore_rest
     Ignores the rest of the labeled arguments following this flag.

   --version
     Displays version information and exits.

   -h,  --help
     Displays usage information and exits.

   <std::string>
     (required)  First index argument is an image

   <std::string>
     (required)  Second index argument is an image


   Description: Shows one of each type of parameter.

   Author(s): Daniel Blezek (GE), Bill Lorensen (GE)

   Acknowledgements: This work is part of the National Alliance for Medical
   Image Computing (NAMIC), funded by the National Institutes of Health
   through the NIH Roadmap for Medical Research, Grant U54 EB005149.
```

**Comment by jcfr** [comment]
Outstanding. Looks good :+1: 

Next, would be nice to add a simple test.

**Comment by cdeepakroy** [comment]
@jcfr shall i version bump to 1.3 and put the new version on pypi?

Also, i want to add a `mode` or `language` element to the xml spec which says which language is the CLI written in. What do you think would be the best way to do this?

**Comment by jcfr** [comment]
@cdeepakroy Bumping to 1.3 makes sense.

@hmeine Could you grant me access to also upload the package ?

**Comment by hmeine** [comment]
@jcfr: Sure. Is it jcfr on pypi, too? I hope so.

**Comment by jcfr** [comment]
Thanks @hmeine Indeed, jcfr is my account on pypi.  Which command do you use to upload the release ? I will add it to the documentation.

**Comment by hmeine** [comment]
Nothing special – `python setup.py register sdist upload --sign`, I believe. My guess is that you know a better / more modern way? ;-)

**Pull request merged**
